# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gnome_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(max_length=40)),
                ('female', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Human_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(max_length=40)),
                ('female', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=15)),
            ],
        ),
    ]
