# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0002_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_name',
            name='race',
        ),
        migrations.DeleteModel(
            name='First_name',
        ),
    ]
