# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0002_auto_20170311_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appearance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personailty1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personailty', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personailty2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personailty', models.CharField(max_length=40)),
            ],
        ),
    ]
