# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0003_appearance_personailty1_personailty2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gnome_last_names',
            new_name='Gnome_female_name',
        ),
        migrations.RenameModel(
            old_name='Human_last_names',
            new_name='Gnome_last_name',
        ),
        migrations.RenameModel(
            old_name='Human_male_names',
            new_name='Gnome_male_name',
        ),
        migrations.RenameModel(
            old_name='Human_female_names',
            new_name='Human_female_name',
        ),
        migrations.RenameModel(
            old_name='Gnome_female_names',
            new_name='Human_last_name',
        ),
        migrations.RenameModel(
            old_name='Gnome_male_names',
            new_name='Human_male_name',
        ),
    ]
