# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0003_auto_20170312_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personailty2',
            new_name='Personality1',
        ),
        migrations.RenameModel(
            old_name='Personailty1',
            new_name='Personality2',
        ),
    ]
