# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0004_auto_20170311_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Races',
            new_name='race',
        ),
    ]
