# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0004_auto_20170312_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building_name_first',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Building_name_last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Building_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingType', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='building_name_last',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Building_type'),
        ),
        migrations.AddField(
            model_name='building_name_first',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Building_type'),
        ),
    ]
