# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0005_auto_20170312_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orc_male_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Race')),
            ],
        ),
    ]
