# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0005_auto_20170312_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building_name_first',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='building_name_last',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
