# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0006_orc_male_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc_male_name',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Race'),
        ),
    ]
