# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0007_drink_name_drink_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physical_affect_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physAff', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Physical_affect_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physAff', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=20)),
            ],
        ),
    ]
