# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0008_drug_name_drug_type_emotion_item_general_physical_affect_1_physical_affect_2_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_general',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worldgen.Building_type'),
            preserve_default=False,
        ),
    ]
