# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0009_item_general_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_general',
            name='catagory',
        ),
    ]
