# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0010_remove_item_general_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_general',
            name='shops',
            field=models.ManyToManyField(to='worldgen.Building_type'),
        ),
    ]
