# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0011_item_general_shops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_general',
            new_name='Item_gear',
        ),
    ]
