# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0012_auto_20170416_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cost', models.IntegerField()),
                ('damageDieQuant', models.IntegerField()),
                ('damageDieType', models.IntegerField()),
                ('damageType', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
                ('weaponRangeMin', models.IntegerField()),
                ('weaponRangeMax', models.IntegerField()),
                ('shops', models.ManyToManyField(to='worldgen.Building_type')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon_properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponProperty', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item_gear',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_weapon',
            name='weaponProperties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Weapon_properties'),
        ),
    ]
