# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0014_auto_20170416_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon_damage_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponDamageType', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='item_weapon',
            name='damageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldgen.Weapon_damage_type'),
        ),
    ]
