# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0015_auto_20170416_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_weapon',
            name='weaponProperties',
        ),
        migrations.AddField(
            model_name='item_weapon',
            name='weaponProperties',
            field=models.ManyToManyField(to='worldgen.Weapon_properties'),
        ),
    ]
