# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldgen', '0017_auto_20170416_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_weapon',
            name='damageDieQuant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item_weapon',
            name='damageDieType',
            field=models.IntegerField(),
        ),
    ]
